name: Update mirrors

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1/15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        run: |
          bash wireguard.sh

      - name: Commit
        id: commit
        run: |
          git config --local user.email "sengshinlee@gmail.com"
          git config --local user.name "Sengshin Lee"
          git add .
          git commit -m "CST: $(TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")"
        continue-on-error: true

      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1

      - name: Push
        run: |
          git pull
          git push -u origin main
